# Generated by Django 6.0.7 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('hover_image', models.ImageField(blank=True, upload_to='destinations/hover/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='experiences/')),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='funfacts/')),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarqueeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VOYAGE', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Curated journeys that transform travel into art', max_length=300)),
                ('hero_video', models.FileField(blank=True, upload_to='videos/')),
                ('hero_heading_line1', models.CharField(default='Beyond the', max_length=200)),
                ('hero_heading_line2', models.CharField(default='Horizon', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Curated journeys that transform travel into art')),
                ('hero_cta_text', models.CharField(default='Begin Your Journey', max_length=100)),
                ('about_overline', models.CharField(blank=True, default='MADE WITH PASSION', max_length=200)),
                ('about_heading', models.CharField(blank=True, default='We Design Emotion', max_length=200)),
                ('about_text', models.TextField(blank=True, default='We believe that travel is not about destinations — it is about feelings. Every journey we craft is a conversation between you and the world, shaped by curiosity, wonder, and the pursuit of something extraordinary.')),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('email', models.EmailField(blank=True, default='hello@voyagetravel.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=20)),
                ('address', models.TextField(blank=True, default='Mumbai, Maharashtra, India')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(default='+', max_length=10)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_destination', models.CharField(max_length=200)),
                ('author_image', models.ImageField(blank=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
